### ISSUE TITLE
Wrong type hint for `Then.validate_data()` method

### ISSUE THREAD

**Issue by remorhaz** [olxxi/ReqFlow#1]
Hello!

In all your examples `Then.validate_data()` method accepts name of the class, but the type hint is `BaseModel` and type checker reports error. Perhaps it should be replaced with `Type[BaseModel]`.

**Comment by olxxi** [comment]
Hello! 

Thank you for pointing that out! Fixed in https://github.com/olxxi/ReqFlow/commit/1aef53fa7bda73e922d17bb166bcb2b1881fd4c3 and pushed to PyPI.

`pip install ReqFlow==1.0.5a0`
